config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('qasite.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('qa.urls', namespace='qa')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

qa/urls.py
# -*- coding: utf-8 -*-
"""Urls for entrance."""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from .question_entry import (
    QuestionCreateView, QuestionUpdateView,
    QuestionDeleteView, QuestionListView,
    QuestionFormatExport
)
from .views import ArticleListView, LevelUpView
from .quiz import QuizView
from .api import (
    StartQuizApi, QuestionApi,
    QuestionAttemptCreate, ArticleDetailViewAPI,
    ArticleHistoryCreate
)

urlpatterns = [
    url(
        regex=r'^$',
        view=ArticleListView.as_view(),
        name='home'
    ),
    url(
        regex=r'^api/article/(?P<article_id>[-\d]+)/$',
        view=ArticleDetailViewAPI.as_view(),
        name='article-detail'
    ),
    url(
        regex=r'^question/create/$',
        view=QuestionCreateView.as_view(),
        name='question-create'
    ),
    url(
        regex=r'^question/update/(?P<id>[-\d]+)/$',
        view=QuestionUpdateView.as_view(),
        name='question-update'
    ),
    url(
        regex=r'^question/delete/(?P<id>[-\w]+)/$',
        view=QuestionDeleteView.as_view(),
        name='question-delete'
    ),
    url(
        regex=r'^question/list/$',
        view=QuestionListView.as_view(),
        name='qlist'
    ),
    url(
        regex=r'^question/format/export/$',
        view=QuestionFormatExport.as_view(),
        name='question-format-export'
    ),
    url(
        regex=r'^quiz/(?P<article_id>[-\w]+)/$',
        view=QuizView.as_view(),
        name='start-quiz'
    ),
    url(
        regex=r'^level/up/$',
        view=LevelUpView.as_view(),
        name='level-up'
    ),
    url(
        regex=r'^api/quiz/start/(?P<slug>[-\w]+)/$',
        view=StartQuizApi.as_view(),
        name='start_quiz_api'
    ),
    url(
        regex=r'^api/question/(?P<id>[-\d]+)/$',
        view=QuestionApi.as_view(),
        name='question_api'
    ),
    url(
        regex=r'^api/question/attempt/$',
        view=QuestionAttemptCreate.as_view(),
        name='question_attempt_create'
    ),
    url(
        regex=r'^api/article-history/(?P<article_id>[-\d]+)/$',
        view=ArticleHistoryCreate.as_view(),
        name='article_history'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qasite/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

qasite/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from qa.models import Level


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    level = models.ForeignKey(Level, verbose_name=_("level"), null=True, blank=True)
    # read_articles =
    # list of read articles

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

qasite/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

qasite/templates/article.html
{% extends "base.html" %}

{% block content %}
<h1>{{article}}</h1>

<div class="row">
	<div class="col-md-12">
	{% for page in pages %}
	<div class="col-md-12">
		{{page|safe}}
	</div>
	{% endfor %}
	</div>
</div>
{% endblock content %}

qasite/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
<head>

  <!-- SITE TITTLE -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Home - Reading Comprehension App{% endblock title %}</title>
  
  <!-- PLUGINS CSS STYLE -->
  <link href="/static/plugins/jquery-ui/jquery-ui.css" rel="stylesheet">
  <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/static/plugins/rs-plugin/css/settings.css" media="screen">
  <link rel="stylesheet" type="text/css" href="/static/plugins/selectbox/select_option1.css">
  <link rel="stylesheet" type="text/css" href="/static/plugins/owl-carousel/owl.carousel.css" media="screen">
  <link rel="stylesheet" type="text/css" href="/static/plugins/isotope/jquery.fancybox.css">
  <link rel="stylesheet" type="text/css" href="/static/plugins/isotope/isotope.css">
  
  <!-- GOOGLE FONT -->
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Dosis:400,300,600,700' rel='stylesheet' type='text/css'>

  <!-- CUSTOM CSS -->
  <link href="/static/css/kids.css" rel="stylesheet">

  <!-- Icons -->
  <link rel="shortcut icon" href="/static/img/favicon.png">
    {% block css %}
    {% endblock %}
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>
  <div class="main-wrapper">
    <!-- HEADER -->
    <header id="pageTop">
      <!-- COLOR BAR -->
      <div class="container-fluid color-bar top-fixed clearfix">
        <div class="row">
          <div class="col-sm-1 col-xs-2 bg-color-1">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-2">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-3">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-4">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-5">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-6">fix bar</div>
          <div class="col-sm-1 bg-color-1 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-2 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-3 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-4 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-5 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-6 hidden-xs">fix bar</div>
        </div>
      </div>

      <!-- TOP INFO BAR -->
      <div class="top-info-bar bg-color-7 hidden-xs">
        <div class="container">
          <div class="row">
            <div class="col-sm-7">
              <ul class="list-inline topList">
              {% if request.user.is_superuser %}
                <li><i class="fa fa-book bg-color-1" aria-hidden="true"></i><a href="{% url 'qa:qlist' %}">Question Bank</a></li>
                <li><i class="fa fa-user bg-color-2" aria-hidden="true"></i><a href="/admin/">Admin</a></li>
              {% endif %}
              </ul>
            </div>
            <div class="col-sm-5">
              <ul class="list-inline functionList">
                {% if request.user.is_authenticated %}
                <li><a href="#">Welcome {{request.user.get_full_name}} !</a></li>
                <li><i class="fa fa-sign-out bg-color-5" aria-hidden="true"></i> <a href="{% url 'account_logout' %}">Log Out</a></li>
                {% else %}
                <li><i class="fa fa-unlock-alt bg-color-5" aria-hidden="true"></i> <a href="{% url 'account_login' %}" data-toggle="modal" >Login</a><span>or</span><a href="{% url 'account_signup' %}" data-toggle="modal">Create an account</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- NAVBAR -->
      <nav id="menuBar" class="navbar navbar-default lightHeader" role="navigation">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img class="img-responsive" src="/static/img/logo-school.png" alt="Kidz School"></a>
          </div>

        </div>
      </nav>
    </header>
    <!-- LIGHT SECTION -->
    <section class="full-width clearfix" style="min-height: 600px;background-color: #f5f5f5;padding: 20px 0;">
      <div class="container">
      {% comment %}
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}
      {% endcomment %}

      {% block content %}
      {% endblock content %}
      </div>
    </section>
    <!-- FOOTER -->
    <footer>
      <!-- COLOR BAR -->
      <div class="container-fluid color-bar clearfix">
        <div class="row">
          <div class="col-sm-1 col-xs-2 bg-color-1">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-2">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-3">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-4">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-5">fix bar</div>
          <div class="col-sm-1 col-xs-2 bg-color-6">fix bar</div>
          <div class="col-sm-1 bg-color-1 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-2 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-3 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-4 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-5 hidden-xs">fix bar</div>
          <div class="col-sm-1 bg-color-6 hidden-xs">fix bar</div>
        </div>
      </div>
      <!-- FOOTER INFO AREA -->
      <div class="footerInfoArea full-width clearfix" style="background-image: url(/static/img/footer/footer-bg-1.png);">
        <div class="container">
          <div class="row">
            <div class="col-sm-2">
            </div>
            <div class="col-sm-3 col-xs-12">
              <div class="footerTitle">
                <a href="index-v1.html"><img src="/static/img/logo-footer.png"></a>
              </div>
              <div class="footerInfo">
                <p>Reading Comprehension App is the best way to get your kids get interested in their study.</p>
                <p>Explore around and let us know if you are interested in buying our service.</p>
              </div>
            </div>
            <div class="col-sm-4">
              
            </div>
            <div class="col-sm-3 col-xs-12">
              <div class="footerTitle">
                <h4>Useful Links</h4>
              </div>
              <div class="footerInfo">
                <ul class="list-unstyled footerList">
                  <li>
                    <a href="/">
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>Reading Comprehension App
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-angle-double-right" aria-hidden="true"></i>Contact Us
                    </a>
                  </li>
                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
      <!-- COPY RIGHT -->
      <div class="copyRight clearfix">
        <div class="container">
          <div class="row">
            <div class="col-sm-5 col-sm-push-7 col-xs-12">
              <ul class="list-inline">
                <li><a href="#" class="bg-color-1"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-2"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-3"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-4"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
                <li><a href="#" class="bg-color-5"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
              </ul>
            </div>
            <div class="col-sm-7 col-sm-pull-5 col-xs-12">
              <div class="copyRightText">
                <p>© 2016 Copyright Reading Comprehension App.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <div class="scrolling">
    <a href="#pageTop" class="backToTop hidden-xs" id="backToTop"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
  </div>

{% block modal %}{% endblock modal %}
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="/static/plugins/jquery-ui/jquery-ui.js"></script>
  <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
  <script src="/static/plugins/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
  <script src="/static/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
  <script src="/static/plugins/selectbox/jquery.selectbox-0.1.3.min.js"></script>
  <script src="/static/plugins/owl-carousel/owl.carousel.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
  <script src="/static/plugins/counter-up/jquery.counterup.min.js"></script>
  <script src="/static/plugins/isotope/isotope.min.js"></script>
  <script src="/static/plugins/isotope/jquery.fancybox.pack.js"></script>
  <script src="/static/plugins/isotope/isotope-triger.js"></script>
  <script src="/static/plugins/countdown/jquery.syotimer.js"></script>
  <script src="/static/plugins/google-custom-map/google-map.js"></script>
  <script src="http://maps.google.com/maps/api/js?key=AIzaSyAjUY8rnvqvQmnUvnztrDgnIpQTLxidt18&callback=initMap"></script>
  <script src="/static/plugins/velocity/velocity.min.js"></script>
  <script src="/static/plugins/smoothscroll/SmoothScroll.js"></script>
  <script src="/static/js/custom.js"></script>

  {% block javascript %}
  {% endblock javascript %}

</body>

</html>

qasite/templates/listquestions.html
{% extends "base.html" %}
{% load staticfiles %}
{% load get_range %}
{% block title %} Question Bank {% endblock title %}

{% block content %}
    <h1>Question Bank</h1>
<div class="row">
    {% if import_msg %} 
        <div class=" col-sm-12 alert alert-success" role="alert">
            {{import_msg}}
        </div>        
    {% endif %}
    {% if error_messages %} 
      {% for err_msg in error_messages %}
        <div class=" col-sm-12 alert alert-danger" role="alert">
            {{err_msg}}
        </div>        
      {% endfor %}
    {% endif %}
    {% if request.GET.deleted %} 
        <div class=" col-sm-12 alert alert-success" role="alert">
            Congratulations question has been deleted successfully.
        </div>        
    {% endif %}
    {% if request.GET.updated %} 
        <div class=" col-sm-12 alert alert-success" role="alert">
            Congratulations question has been updated successfully.
        </div>        
    {% endif %}
    <div class="col-sm-12" style="margin-top:30px;margin-bottom:1%;">
        <div class="col-sm-6 col-sm-push-6" style="margin-bottom: 10px;">
          <a href="{% url 'qa:question-create' %}" class="btn btn-primary" style="float: right;">Add Question</a>
          <a href="#" class="btn btn-secondary" style="float: right; margin-right: 20px;" onclick="import_modal()">Import Questions</a>
          <a href="{% url 'qa:question-format-export' %}" class="btn btn-secondary" style="float: right; margin-right: 20px;">Export</a>
        </div>
    </div>
    <div class="col-sm-3 highlight" style="margin-top:10px;margin-bottom:10px;border: 1px solid #ccc; padding: 10px;border-radius: 15px;">
        <div class="row">
        <div class="col-sm-12">
            <form action="." method='GET' style="margin-top:30px;margin-bottom:1%;">
            <div>
              <p style="font-size: 16px;font-weight: 800;display:inline;">Filters</p>
              <button type="submit" class="btn btn-primary" style="float: right;display: inline;margin-top:-10px;"><i class="fa fa-search"></i></button>
            </div>
            <hr/>
                <div style="margin-bottom: 10px;">
                    <div class="input-group">
                        <input type="text" id="searchText" value="{{request.GET.q}}" class="form-control" placeholder="Search for..." name="q">
                    </div>
                </div>
                <div class="filter-title">
                    {% for article in articles %}
                      <input class="topicInput" value="{{article.id}}" type="checkbox" aria-label="English" name="topic" {% if article.id in selected_topics %} checked="checked" {% endif %}>
                      <span class="item-title">{{article.title}}</span>
                      <br/>
                    {% endfor %}
                </div>
            </form>
        </div>          
        </div>
    </div>
    <div class="col-sm-9 " style="margin-top:10px;margin-bottom:10px;">
            {% for quest in object_list %}
            <div class="highlight" style="margin-top:10px;min-height:100px;">
                <p> {{forloop.counter|add:"-1"|add:start}}) <a href="{% url 'qa:question-update' quest.id %}">{{quest.text}}</a></p>
                <span class="label label-default" style="float:left"> Article: {{quest.article}} </span>
                <span class="label label-default" style="float:right"> Category: {{quest.category}} </span>
            </div>
            <hr>
            {% empty %}
              <h2>No Questions !</h2>
            {% endfor %}
    <div class="row">
      <div class="col-md-6 pagination">
          <p style="padding-left:14px;">Showing {{start}} to {{end}} of {{total}} entries</p>
      </div>      
      <div class="col-md-6">
      <nav>
        <ul class="pagination pull-right">
        {% if object_list.has_previous %}
          <li class="page-item">
            <a class="page-link" href="{{current_path}}page={{ object_list.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
        {% endif %}
          {% for i in object_list.paginator.num_pages|get_range %}
            {% if forloop.counter == object_list.number %}
            <li class="page-item active">
              <a class="page-link" href="#">{{forloop.counter}} <span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="{{current_path}}page={{forloop.counter}}">{{forloop.counter}}</a></li>
            {% endif %}
          {% endfor %}
          {% if object_list.has_next %}
          <li class="page-item">
            <a class="page-link" href="{{current_path}}page={{object_list.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      </div>
      </div>
    </div>
</div>
{% endblock %}

{% block modal %}
<div class="modal fade" id="questionsImportModal" style="margin-top: 12%;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Import Questions in Bulk</h4>
            </div>
            <div class="modal-body">
                <div>
                    <label>You are going to import Excel file for creating questions in bulk:</label>
                </div>
                <form class="form-inline row" id="marksImportForm" method="POST" action="." enctype='multipart/form-data' style="margin-top: 20px;">{% csrf_token %}
                    <div class="form-group col-sm-12">
                        <label for="inputFile">File Input: </label>
                        <input type="file" id="inputFile" class="form-control" name="inputFile" accept=".xlsx,.xls,application/vnd.ms-excel" required="required"><br>
                        <p class="help-block" id="file-help">Please select the excel file here.</p>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-secondary" onclick="submitImportFile()">Import</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
{% endblock modal %}

{% block javascript %}
<script type="text/javascript">
function import_modal(){
  $('#questionsImportModal').modal();
}

function submitImportFile(){
  if($('#inputFile').val() == ""){
    $('#file-help').attr('style', 'color: red');
  }
  else{
    $('#marksImportForm').submit();
  }
}

</script>
{% endblock javascript %}